OdamOlsun/OdamOlsunWeb/Areas/Admin/Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using OdamOlsun.BL.Managers.Abstract;
using OdamOlsun.BL.Managers.Concrete;
using OdamOlsun.Entities.Models.Concrete;
using OdamOlsun.Utilities;
using OdamOlsunWeb.Models.ViewModels;
using X.PagedList.Mvc.Core;
using X.PagedList;
using Microsoft.EntityFrameworkCore;
namespace OdamOlsunWeb.Controllers
{
    [Area("Admin")]
    // Eğer authorize kısmını action ın üstüne yazarsan sadece ilgili aksiyonu kısıtlar
    [Authorize(Roles = SD.Role_Admin)]
    public class IlanController : Controller
    {
        private readonly IIlanManager _ilanManager;
        private readonly IResimManager _resimManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public IlanController(IIlanManager ilanManager, IResimManager resimManager, IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _ilanManager = ilanManager;
            _resimManager = resimManager;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;

        }
        public async Task<IActionResult> Index(int? page)
        {
            var ilanlar = await _ilanManager.GetAll().ToList().ToPagedListAsync(page ?? 1, 10);
            return View(ilanlar);
        }

        public async Task<IActionResult> Create()
        {
            IlanVM ilanVM = new IlanVM();
            return View(ilanVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(IlanVM obj, List<IFormFile> Resims)
        {
            if (ModelState.IsValid)
            {   //ilanı veritabanına kaydetme!
                var userId = _userManager.GetUserId(User);

                Ilan ilan = new Ilan()
                {
                    Id = obj.Id,
                    Title = obj.Title,
                    Size = obj.Size,
                    Price = obj.Price,
                    Deposit = obj.Deposit,
                    Address = obj.Address,
                    NumberOfRooms = obj.NumberOfRooms,
                    NumberOfFloorOfBuild = obj.NumberOfFloorOfBuild,
                    FloorOfHouse = obj.FloorOfHouse,
                    AgeOfBuild = obj.AgeOfBuild,
                    Furnished = obj.Furnished,
                    Cigarette = obj.Cigarette,
                    Animal = obj.Animal,
                    RoomAndHomeDetails = obj.RoomAndHomeDetails,
                    Il = obj.Il,
                    Ilce = obj.Ilce,
                    Semt = obj.Semt,
                    ApplicationUserId = userId

                };
                await _ilanManager.InsertAsync(ilan);

                //resimleri kaydetme
                if (Resims != null && Resims.Count > 0)
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;

                    foreach (var formFile in Resims)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
                        string productPath = Path.Combine(wwwRootPath, @"images/ilan");
                        using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                        {
                            await formFile.CopyToAsync(fileStream);
                        }
                        var resim = new Resim
                        {
                            Url = @"/images/ilan/" + fileName, //"/uploads/" + formFile.FileName,
                            IlanId = ilan.Id
                        };
                        await _resimManager.InsertAsync(resim);
                    }
                }


                TempData["success"] = "İlan Başarıyla Oluşturuldu";
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            Ilan obj = _ilanManager.GetAllInclude(u => u.Resims).FirstOrDefault(u => u.Id == id);

            if (obj != null)
            {
                _ilanManager.DeleteAsync(obj);
                if (obj.Resims != null)
                {
                    foreach (var resim in obj.Resims)
                    {
                        var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, resim.Url.TrimStart('/'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                }
                TempData["success"] = "İlan Başarıyla Silindi";

            }

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Ilan? ilan = await _ilanManager.GetAllInclude(p => p.Resims).FirstOrDefaultAsync(u => u.Id == id);

            if (ilan == null)
            {
                return NotFound();
            }
            IlanVM ilanVM = new IlanVM
            {
                Title = ilan.Title,
                Size = ilan.Size,
                Price = ilan.Price,
                Deposit = ilan.Deposit,
                Address = ilan.Address,
                NumberOfRooms = ilan.NumberOfRooms,
                NumberOfFloorOfBuild = ilan.NumberOfFloorOfBuild,
                FloorOfHouse = ilan.FloorOfHouse,
                AgeOfBuild = ilan.AgeOfBuild,
                Furnished = ilan.Furnished,
                Cigarette = ilan.Cigarette,
                Animal = ilan.Animal,
                RoomAndHomeDetails = ilan.RoomAndHomeDetails,
                Il = ilan.Il,
                Ilce = ilan.Ilce,
                Semt = ilan.Semt
            };

            return View(ilanVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(IlanVM obj)
        {
            if (ModelState.IsValid)
            {
                Ilan ilan = await _ilanManager.GetByIdAsync(obj.Id);

                if (ilan == null)
                {
                    return NotFound();
                }

                ilan.Title = obj.Title;
                ilan.Size = obj.Size;
                ilan.Price = obj.Price;
                ilan.Deposit = obj.Deposit;
                ilan.Address = obj.Address;
                ilan.NumberOfRooms = obj.NumberOfRooms;
                ilan.NumberOfFloorOfBuild = obj.NumberOfFloorOfBuild;
                ilan.FloorOfHouse = obj.FloorOfHouse;
                ilan.AgeOfBuild = obj.AgeOfBuild;
                ilan.Furnished = obj.Furnished;
                ilan.Cigarette = obj.Cigarette;
                ilan.Animal = obj.Animal;
                ilan.RoomAndHomeDetails = obj.RoomAndHomeDetails;
                ilan.Il = obj.Il;
                ilan.Ilce = obj.Ilce;
                ilan.Semt = obj.Semt;

                await _ilanManager.UpdateAsync(ilan);
                TempData["success"] = "İlan Başarıyla Güncellendi";


                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

OdamOlsun/OdamOlsunWeb/Areas/User/Controllers/IlanlarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OdamOlsun.BL.Managers.Abstract;
using OdamOlsun.Entities.Models.Concrete;
using OdamOlsunWeb.Models.ViewModels;
using OdamOlsun.Utilities;
using Microsoft.AspNetCore.Authorization;




namespace OdamOlsunWeb.Areas.User.Controllers
{
    [Area("User")]
    public class IlanlarController : Controller
    {
        private readonly ILogger<IlanlarController> _logger;

        private readonly IIlanManager _ilanManager;
        private readonly IResimManager _resimManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;



        public IlanlarController(ILogger<IlanlarController> logger, UserManager<ApplicationUser> userManager, IIlanManager ilanManager, IResimManager resimManager, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            _userManager = userManager;
            _ilanManager = ilanManager;
            _resimManager = resimManager;
            _webHostEnvironment = webHostEnvironment;

        }
        
        [HttpGet]
        [Authorize(Roles = SD.Role_Customer + "," + SD.Role_Admin)]

        public async Task<IActionResult> Index()
        {
            var userId =  _userManager.GetUserId(User);
            IEnumerable<Ilan> ilanlar =await _ilanManager.GetAllInclude(u => u.Resims).Include(u => u.ApplicationUser).Where(i => i.ApplicationUserId == userId).ToListAsync();
            if (ilanlar.Any())
            {
                foreach (var ilan in ilanlar)
                {
                    CityService cityService = new CityService();
                    ilan.Il = cityService.GetIl(Convert.ToInt32(ilan.Il));
                }
                return View(ilanlar);
            }
            return View();
        }

        // [HttpGet]
        // [Authorize(Roles = SD.Role_Customer)]
        // public IActionResult Index(string userId)
        // {
        //     IEnumerable<Ilan> ilanlar = _ilanManager.GetAllInclude(u => u.Resims).Include(u => u.ApplicationUser).Where(i => i.ApplicationUserId == userId).ToList();
        //     if (ilanlar.Any())
        //     {
        //         foreach (var ilan in ilanlar)
        //         {
        //             CityService cityService = new CityService();
        //             ilan.Il = cityService.GetIl(Convert.ToInt32(ilan.Il));
        //         }
        //         return View(ilanlar);
        //     }
        //     return View();
        // }


        public async Task<IActionResult> Details(int id)
        {
            Ilan ilan = await _ilanManager.GetAllInclude(u => u.Resims).Include(u => u.ApplicationUser).FirstOrDefaultAsync(u => u.Id == id);


            if (ilan == null)
            {
                return NotFound();
            }
            CityService cityService = new CityService();
            ilan.Il = cityService.GetIl(Convert.ToInt32(ilan.Il));

            return View(ilan);
        }

        [Authorize(Roles = SD.Role_Customer)]
        public async Task<IActionResult> Delete(int id)
        {
            Ilan obj = await _ilanManager.GetAllInclude(u => u.Resims).FirstOrDefaultAsync(u => u.Id == id);

            if (obj != null)
            {
                await _ilanManager.DeleteAsync(obj);
                if (obj.Resims != null)
                {
                    foreach (var resim in obj.Resims)
                    {
                        var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, resim.Url.TrimStart('/'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                }
                TempData["success"] = "İlan Başarıyla Silindi";
            }
            return RedirectToAction("Index");
        }

                [Authorize(Roles = SD.Role_Customer + "," + SD.Role_Admin)]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Ilan? ilan = await _ilanManager.GetAllInclude(p => p.Resims).FirstOrDefaultAsync(u => u.Id == id);

            if (ilan == null)
            {
                return NotFound();
            }
            IlanVM ilanVM = new IlanVM
            {
                Title = ilan.Title,
                Size = ilan.Size,
                Price = ilan.Price,
                Deposit = ilan.Deposit,
                Address = ilan.Address,
                NumberOfRooms = ilan.NumberOfRooms,
                NumberOfFloorOfBuild = ilan.NumberOfFloorOfBuild,
                FloorOfHouse = ilan.FloorOfHouse,
                AgeOfBuild = ilan.AgeOfBuild,
                Furnished = ilan.Furnished,
                Cigarette = ilan.Cigarette,
                Animal = ilan.Animal,
                RoomAndHomeDetails = ilan.RoomAndHomeDetails,
                Il = ilan.Il,
                Ilce = ilan.Ilce,
                Semt = ilan.Semt
            };

            return View(ilanVM);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Customer)]

        public async Task<IActionResult> Edit(IlanVM obj)
        {
            if (ModelState.IsValid)
            {
                Ilan ilan = await _ilanManager.GetByIdAsync(obj.Id);

                if (ilan == null)
                {
                    return NotFound();
                }

                ilan.Title = obj.Title;
                ilan.Size = obj.Size;
                ilan.Price = obj.Price;
                ilan.Deposit = obj.Deposit;
                ilan.Address = obj.Address;
                ilan.NumberOfRooms = obj.NumberOfRooms;
                ilan.NumberOfFloorOfBuild = obj.NumberOfFloorOfBuild;
                ilan.FloorOfHouse = obj.FloorOfHouse;
                ilan.AgeOfBuild = obj.AgeOfBuild;
                ilan.Furnished = obj.Furnished;
                ilan.Cigarette = obj.Cigarette;
                ilan.Animal = obj.Animal;
                ilan.RoomAndHomeDetails = obj.RoomAndHomeDetails;
                ilan.Il = obj.Il;
                ilan.Ilce = obj.Ilce;
                ilan.Semt = obj.Semt;

                await _ilanManager.UpdateAsync(ilan);
                TempData["success"] = "İlan Başarıyla Güncellendi";

                string userId = _userManager.GetUserId(User); // Dinamik olarak alınıyor.
                string url = $"/User/Ilanlar?userId={userId}";

                return Redirect(url);
            }
            return View();
        }

        [Authorize(Roles = SD.Role_Customer)]

        public IActionResult Create()
        {
            IlanVM ilanVM = new IlanVM();
            return View(ilanVM);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Customer)]

        public async Task<IActionResult> Create(IlanVM obj, List<IFormFile> Resims)
        {
            if (ModelState.IsValid)
            {   //ilanı veritabanına kaydetme!
                var userId = _userManager.GetUserId(User);

                Ilan ilan = new Ilan()
                {
                    Id = obj.Id,
                    Title = obj.Title,
                    Size = obj.Size,
                    Price = obj.Price,
                    Deposit = obj.Deposit,
                    Address = obj.Address,
                    NumberOfRooms = obj.NumberOfRooms,
                    NumberOfFloorOfBuild = obj.NumberOfFloorOfBuild,
                    FloorOfHouse = obj.FloorOfHouse,
                    AgeOfBuild = obj.AgeOfBuild,
                    Furnished = obj.Furnished,
                    Cigarette = obj.Cigarette,
                    Animal = obj.Animal,
                    RoomAndHomeDetails = obj.RoomAndHomeDetails,
                    Il = obj.Il,
                    Ilce = obj.Ilce,
                    Semt = obj.Semt,
                    ApplicationUserId = userId

                };
                await _ilanManager.InsertAsync(ilan);

                //resimleri kaydetme
                if (Resims != null && Resims.Count > 0)
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;

                    foreach (var formFile in Resims)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
                        string productPath = Path.Combine(wwwRootPath, @"images/ilan");
                        using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                        {
                            formFile.CopyTo(fileStream);
                        }
                        var resim = new Resim
                        {
                            Url = @"/images/ilan/" + fileName, //"/uploads/" + formFile.FileName,
                            IlanId = ilan.Id
                        };
                        await _resimManager.InsertAsync(resim);
                    }
                }


                TempData["success"] = "İlan Başarıyla Oluşturuldu";
                // Dinamik olarak alınıyor.
                string url = $"/User/Ilanlar?userId={userId}";
                return Redirect(url);
            }
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

OdamOlsun/OdamOlsunWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Odam Olsun</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/OdamOlsunWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="User" asp-controller="Home" asp-action="Index"><i
                        class="bi bi-house-fill"></i> Odam Olsun</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="User" asp-controller="Home"
                                asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Ilanlar" asp-action="Index">İlanlar</a>
                        </li>
                        <!-- Eğer admin giriş yaptıysa -->
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <div class="dropdown">
                                <button type="button" class="btn btn-primary bg-primary border-0 dropdown-toggle"
                                    data-bs-toggle="dropdown">Manage
                                </button>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Ilan"
                                            asp-action="Index">İlanlar</a>
                                    </li>
                                </ul>
                            </div>
                        }
                    </ul>
                    @if (User.IsInRole(SD.Role_Customer))
                    {
                        <a class="text-white text-decoration-none px-2" asp-area="User" asp-controller="Ilanlar"
                            asp-action="Create"><i class="bi bi-plus-circle"></i> İlan Ekle</a>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <footer class="border-top border-black bg-secondary bg-opacity-50 mt-5">
        <div class="container mt-5 ">
            <div class="row">
                <div class="col-lg-4 col-md-3 col-sm-4 col-xs-6">
                    <div class="_kl_ds_we">
                        <div class="head-footer">
                            <h4 class="border-bottom border-black">Odam Olsun</h4>
                            <p>Taşınmak istediğiniz şehirdeki pahalı kiralardan kurtulup size uygun
                                odayı makul fiyatlara kiralayabileceğiniz veya evinizdeki bir odayı
                                kiraya verebileceğiniz kişileri bulmanızı sağlayan web sitesi.
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-3 col-sm-4 col-xs-6">
                    <div class="_kl_ds_we">
                        <div class="head-footer col-12 row">
                            <h4 class="border-bottom border-black">POPÜLER İLLER</h4>
                            <a asp-controller="Ilanlar" asp-action="Index" asp-route-il="34" class="d-block col-6"><i
                                    class="bi bi-geo-alt"></i>İstanbul</a>
                            <a asp-controller="Ilanlar" asp-action="Index" asp-route-il="6" class="d-block col-6"><i
                                    class="bi bi-geo-alt"></i>Ankara</a>
                            <a asp-controller="Ilanlar" asp-action="Index" asp-route-il="35" class="d-block col-6"><i
                                    class="bi bi-geo-alt"></i>İzmir</a>
                            <a asp-controller="Ilanlar" asp-action="Index" asp-route-il="16" class="d-block col-6"><i
                                    class="bi bi-geo-alt"></i>Bursa</a>
                            <a asp-controller="Ilanlar" asp-action="Index" asp-route-il="7" class="d-block col-6"><i
                                    class="bi bi-geo-alt"></i>Antalya</a>
                            <a asp-controller="Ilanlar" asp-action="Index" asp-route-il="26" class="d-block col-6"><i
                                    class="bi bi-geo-alt"></i>Eskişehir</a>

                        </div>

                    </div>
                </div>
                <div class="col-lg-4 col-md-3 col-sm-4 col-xs-6">
                    <div class="_kl_ds_we">
                        <div class="head-footer">
                            <h4 class="border-bottom border-black">BİZE ULAŞIN</h4>
                            <ul class="un-hover">
                                <li><i class="bi bi-geo-alt-fill"></i> Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9,
                                    34353 Beşiktaş/İstanbul</li>
                                <li><i class="fas fa-mobile-alt"></i> +90 538 030 92 97</li>
                                <li><i class="far fa-envelope"></i> ozturkemir2001@gmail.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-12 border-top mt-2 border-dark mb-0">
                    <div class="row _pl_we_sq">
                        <div class="col-12 mt-2 text-center">
                            <div class="last-01">
                                <p> © OdamOlsun. 2024 Bütün Hakları Saklıdır. Made by <a href="https://github.com/EmirOzturk01" style="text-decoration: none;" target="_blank">Emir Öztürk</a> | 
                                <a asp-controller="Home" asp-action="Privacy" class="text-primary">Privacy</a>

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

OdamOlsun/OdamOlsunWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]');
    </script>
}